### ISSUE TITLE
Views / UI Refactoring

### ISSUE THREAD

**Issue by Souhail-5** [Spartacvs/nao-projet#9]
Je vais procéder à un refactoring des views et de leur architecture :

- les /app/Resources/views seront déplacées dans le CoreBundle
- un seul layout.html.twig dans CoreBundle ; qui sera hérité par les autres vues et bundles
- un dossier /src/Nao/CoreBundle/Resources/views/**Widgets** contenant : header + footer + Newsletter-section + page-heading (breadcrumb)

**Comment by Souhail-5** [comment]
Il faut aussi modifier comment les variables des vues sont définis : les définir dans .html.twig et non pas dans le contrôleur ; le plus possible.

**Comment by Spartacvs** [comment]
Je ne comprends ne connais pas ce procédé. Je te laisse le faire ?

**Comment by Souhail-5** [comment]
Je vais le faire petit à petit ce refactoring ; pour l'instant je m'attarde sur le CoreBundle

**Comment by Souhail-5** [comment]
J'ai fini ça et maintenant je vais entamer la même chose pour le UserBundle
